name: Deploy to Server
on:
  push:
    branches: [update] # or your target branch

jobs:
  deploy:
    runs-on: ubuntu-24.04.1
    steps:
      - name: SSH into Server & Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }} # Add server IP as a secret
          username: ${{ secrets.SSH_USERNAME }} # e.g., 'root'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/skooltym_admin
            git pull origin main
            npm install
            npm run build
            pm2 restart skooltym_admin 
        # Or systemctl restart nextjs.service